"""Add embedding column to research_items

Revision ID: 03504786642b
Revises: 339ea454198d
Create Date: 2025-03-11 19:20:59.928085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03504786642b'
down_revision: Union[str, None] = '339ea454198d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_items', sa.Column('embedding', sa.Text(), nullable=True))
    op.alter_column('research_items', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('research_items', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('research_items', 'embedding')
    # ### end Alembic commands ###
