"""Add timestamp to research_items

Revision ID: 339ea454198d
Revises: c39ffb85a325
Create Date: 2025-03-07 16:56:16.844666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339ea454198d'
down_revision: Union[str, None] = 'c39ffb85a325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_items', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_items', 'timestamp')
    # ### end Alembic commands ###
